apiVersion: 1
groups:
    - orgId: 1
      name: HoneyPot
      folder: Alert Notifications
      interval: 10s
      rules:
        - uid: b98eef24-262b-4510-bb23-3fb178c2e82b
          title: HoneyPot
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: c46a2f2b-b8f1-45d4-b8aa-aeabd2d74930
              model:
                editorMode: code
                format: table
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                rawQuery: true
                rawSql: |-
                    SELECT COUNT(*) AS attacks
                    FROM honeypot_logs
                    WHERE timestamp > NOW() - INTERVAL '1 minute';
                refId: A
                sql:
                    columns:
                        - parameters: []
                          type: function
                    groupBy:
                        - property:
                            type: string
                          type: groupBy
                    limit: 50
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 0s
          labels:
            team: honeypot
          isPaused: false
    - orgId: 1
      name: PiAlerts
      folder: Alert Notifications
      interval: 10s
      rules:
        - uid: b335a0e9-3a78-47e2-a233-50d779080bff
          title: Container2 Offline Alert
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: c46a2f2b-b8f1-45d4-b8aa-aeabd2d74930
              model:
                editorMode: code
                format: table
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                rawQuery: true
                rawSql: |-
                    SELECT
                      EXTRACT(
                        EPOCH
                        FROM
                          (NOW() - MAX(timestamp))
                      ) AS seconds_since_update
                    FROM
                      system_stats
                    WHERE
                      container_name = 'monitor2';
                refId: A
                sql:
                    columns:
                        - parameters: []
                          type: function
                    groupBy:
                        - property:
                            type: string
                          type: groupBy
                    limit: 50
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 60
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 10s
          annotations:
            summary: Sends alert if second container is down for longer then 60 Seconds
          isPaused: false
        - uid: b77237bf-b38c-4c6d-b663-f21aeb11dcd1
          title: Container3 Offline Alert
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: c46a2f2b-b8f1-45d4-b8aa-aeabd2d74930
              model:
                editorMode: code
                format: table
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                rawQuery: true
                rawSql: |-
                    SELECT
                      EXTRACT(
                        EPOCH
                        FROM
                          (NOW() - MAX(timestamp))
                      ) AS seconds_since_update
                    FROM
                      system_stats
                    WHERE
                      container_name = 'monitor3';
                refId: A
                sql:
                    columns:
                        - parameters: []
                          type: function
                    groupBy:
                        - property:
                            type: string
                          type: groupBy
                    limit: 50
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 60
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 10s
          annotations:
            summary: Sends alert if third container is down for longer then 60 Seconds
          isPaused: false
        - uid: b0b4fd80-ded4-45f9-90ba-388ec060207e
          title: 'Container1 Offline Alert '
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: c46a2f2b-b8f1-45d4-b8aa-aeabd2d74930
              model:
                editorMode: code
                format: table
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                rawQuery: true
                rawSql: |-
                    SELECT
                      EXTRACT(
                        EPOCH
                        FROM
                          (NOW() - MAX(timestamp))
                      ) AS seconds_since_update
                    FROM
                      system_stats
                    WHERE
                      container_name = 'monitor1';
                refId: A
                sql:
                    columns:
                        - parameters: []
                          type: function
                    groupBy:
                        - property:
                            type: string
                          type: groupBy
                    limit: 50
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 60
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 10s
          annotations:
            summary: Sends alert if first container is down for longer then 60 Seconds
          isPaused: false
