{
 "title": "Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n    timestamp AS \"time\",\n    cpu_usage AS value,\n    container_name AS metric\nFROM system_stats\nWHERE $__timeFilter(timestamp)\n  AND container_name IN ('monitor1','monitor2','monitor3')\nORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n    timestamp AS \"time\",\n    memory_usage AS value,\n    container_name AS metric\nFROM system_stats\nWHERE $__timeFilter(timestamp)\n  AND container_name IN ('monitor1','monitor2','monitor3')\nORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "CPU Temperature °C",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n    timestamp AS \"time\",\n    cpu_temperature AS value,\n    container_name AS metric\nFROM system_stats\nWHERE $__timeFilter(timestamp)\n  AND container_name IN ('monitor1','monitor2','monitor3')\nORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Swap Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n    timestamp AS \"time\",\n    swap_usage AS value,\n    container_name AS metric\nFROM system_stats\nWHERE $__timeFilter(timestamp)\n  AND container_name IN ('monitor1','monitor2','monitor3')\nORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Storage Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n    timestamp AS \"time\",\n    storage_usage AS value,\n    container_name AS metric\nFROM system_stats\nWHERE $__timeFilter(timestamp)\n  AND container_name IN ('monitor1', 'monitor2', 'monitor3')\nORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Container Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n    container_name,\n    CASE\n        WHEN NOW() - MAX(timestamp) > INTERVAL '60 seconds'\n        THEN 'Offline'\n        ELSE 'Online'\n    END AS status,\n    MAX(timestamp) AS last_seen\nFROM system_stats\nWHERE container_name IN ('monitor1','monitor2','monitor3')\nGROUP BY container_name\nORDER BY container_name;"
    }
   ]
  }
 ]
}